export const photoData = {
  PDKT: {
    title: "PDKT Phase",
    photos: [
      { src: "/images/1/1.jpg", caption: "Ini pas kamu ulang tahun" },
      { src: "/images/1/2.jpg", caption: "Bocil bobo" },
      { src: "/images/1/3.jpg", caption: "Dari belakang cantik" },
      { src: "/images/1/4.jpg", caption: "ini First pap ke aku niii" },
      { src: "/images/1/5.jpg", caption: "cantik bener bu" },
      { src: "/images/1/6.jpg", caption: "gemesh deh" },
      { src: "/images/1/7.jpg", caption: "aduduuuh gakuat aku" },
      { src: "/images/1/8.jpg", caption: "bocil menjadi bolang di jakarta" },
      { src: "/images/1/9.jpg", caption: "jempol duluu" },
      { src: "/images/1/10.jpg", caption: "jempol lagii" },
      { src: "/images/1/11.jpg", caption: "jempol lagii 2" },
      { src: "/images/1/12.jpg", caption: "masyaallah pacarin boleh ga siii???" },
      { src: "/images/1/13.jpg", caption: "ni si paling badminton" },
      { src: "/images/1/14.jpg", caption: "manis banget, permennya" },
      { src: "/images/1/15.jpg", caption: "ini sigma dinda dengan dagunya" },
      { src: "/images/1/16.jpg", caption: "assalamualaikum ukhti" },
      { src: "/images/1/17.jpg", caption: "aduh takut dikokop" },
      { src: "/images/1/18.jpg", caption: "jadi kakak kakak undip di sekolah dulu" },
      { src: "/images/1/19.jpg", caption: "jempol lagii 3 cantik beneer" },
      { src: "/images/1/20.jpeg", caption: "our First photobooth" },
      { src: "/images/1/21.jpg", caption: "mbak mbak jawa ini sungguh memikat deh" },
      { src: "/images/1/22.jpg", caption: "nyoblos dulu boss" },
      { src: "/images/1/23.jpg", caption: "ini ni kebiasaan setengah muka" },
    ],
  },
  Jadian: {
    title: "Jadian nih",
    photos: [
      { src: "/images/2/2.jpg", caption: "jadi guguk aja cantik apa lagi jadi pacar aku ya" },
      { src: "/images/2/3.jpg", caption: "cantik banget ya allah pacar akuu" },
      { src: "/images/2/4.jpg", caption: "di pap cantik begini gimana ga meleleh aku" },
      { src: "/images/2/5.jpg", caption: "anjay kayak emo girl" },
      { src: "/images/2/6.jpg", caption: "pipinya gigit boleeh?" },
      { src: "/images/2/7.jpg", caption: "🤩" },
      { src: "/images/2/8.jpg", caption: "jadi ibu ibu sw bisa ni kamu sayang" },
      { src: "/images/2/9.jpg", caption: "di liat liat cantik juga ni cewek" },
      { src: "/images/2/10.jpg", caption: "dari bawah cantik" },
      { src: "/images/2/11.jpg", caption: "jadi ukhti gini cantik" },
      { src: "/images/2/12.jpg", caption: "bobo 2" },
      { src: "/images/2/13.jpg", caption: "utututu gemehnya bociiil" },
      { src: "/images/2/14.jpg", caption: "bobo 3" },
    ],
  },
  Main: {
    title: "Lebaran",
    photos: [
      { src: "/images/3/1.jpg", caption: "nemenin kamu lagi main bareng temen kamu" },
      { src: "/images/3/2.jpg", caption: "gemeh banget ini" },
      { src: "/images/3/3.jpg", caption: "masyaallah nikah yuk dek" },
      { src: "/images/3/4.jpg", caption: "iya ampun iyaa gakuat akuu" },
      { src: "/images/3/5.jpg", caption: "minal aidin wal faidin mohon doa dan restunya papa dan mama din din" },
      { src: "/images/3/6.jpg", caption: "loh heh 🤔" },
      { src: "/images/3/7.jpg", caption: "hihihihihi ternyata pacar aku toh" },
      { src: "/images/3/8.jpg", caption: "stop pipi kamu mau tumpah" },
      { src: "/images/3/9.jpg", caption: "mata kamu cantik banget sayaaang 🫠" },
    ],
  },
  konser: {
    title: "Pacar aku cantik deh",
    photos: [
      { src: "/images/4/1.jpg", caption: "koser pertama banget ni???" },
      { src: "/images/4/2.jpg", caption: "koser kehujanan" },
      { src: "/images/4/3.jpg", caption: "gemeshnyaaa" },
      { src: "/images/4/4.jpg", caption: "fix besok nikah ." },
      { src: "/images/4/5.jpg", caption: "bocil cina" },
      { src: "/images/4/6.jpg", caption: "kak nikahin aku kaaak" },
      { src: "/images/4/7.jpg", caption: "gemeessh bangeeeeet" },
      { src: "/images/4/8.jpg", caption: "fix sekaran otw ngelamar" },
    ],
  },
  love: {
    title: "I Love you always ya baby",
    photos: [
      { src: "/images/5/2.jpg", caption: "winglok time" },
      { src: "/images/5/1.jpg", caption: "cantik beneeer" },
      { src: "/images/5/3.jpg", caption: "dimasakin istri pulang kerja 😎" },
      { src: "/images/5/4.jpg", caption: "melet mulu aku gigit ni" },
      { src: "/images/5/5.jpeg", caption: "hP TEROOOSSS" },
      { src: "/images/5/6.jpg", caption: "pipinya dijagain nanti jatoooh 🫠" },
      { src: "/images/5/7.jpg", caption: "gakuat abang dek 🥵" },
      { src: "/images/5/8.jpg", caption: "aduh dikedipin yang begini enaknya diapain ya" },
      { src: "/images/5/9.jpg", caption: "melet lagi ni aku sentil kali ya" },
      { src: "/images/5/10.jpg", caption: "nah pinter, tapi itu pipinya kenapa mau jatoh??" },
      { src: "/images/5/11.jpg", caption: "aduh duuuh, sini abang nafkahin dek" },
      { src: "/images/5/12.jpg", caption: "sedihnyaaa 🥲" },
      { src: "/images/5/13.jpg", caption: "SIAPA ITU YANG BERANI NYENDER 😡" },
    ],
  },
  cantik: {
    title: "Gemeshnya baby akuh",
    photos: [
      { src: "/images/6/1.jpg", caption: "sumpah deh sayang kamu cantik bangeet" },
      { src: "/images/6/2.jpg", caption: "cantik banget siiiiih" },
      { src: "/images/6/3.jpg", caption: "aduh kedipin lagi ga tu" },
      { src: "/images/6/4.jpg", caption: "🫣" },
      { src: "/images/6/5.jpg", caption: "ampun bu guyu ampuuun" },
      { src: "/images/6/6.jpg", caption: "melet lagi tak totok kamu" },
      { src: "/images/6/7.jpg", caption: "udah dibilangin juga itu pipinya jagain" },
      { src: "/images/6/8.jpg", caption: "photobooth gemaaash" },
      { src: "/images/6/9.jpg", caption: "rambut kami cantik banget siiiih" },
      { src: "/images/6/10.jpg", caption: "harus dirangkul soalnya ada yang bajunya kembaran" },
      { src: "/images/6/11.jpg", caption: "wiih ada pernyaaa" },
      { src: "/images/6/12.jpg", caption: "panas kaaan, main jauh jauh siiih" },
      { src: "/images/6/13.jpg", caption: "Cute baby bocil" },
      { src: "/images/6/14.jpg", caption: "eskim timee" },
      { src: "/images/6/15.jpg", caption: "apa ga seneng di kasih pap begini" },
      { src: "/images/6/16.jpg", caption: "orang ga liatin acaranya malah liat panitianya ini mah" },
      { src: "/images/6/17.jpg", caption: "si cantik yang rajin prokeran" },
      { src: "/images/6/18.jpg", caption: "dewi dari mana inii??" },
      { src: "/images/6/19.jpg", caption: "gemesh naaaa" },
    ],
  },
  mine: {
    title: "Thankyou sayaang",
    photos: [
      { src: "/images/7/1.jpg", caption: "gemesnyaa" },
      { src: "/images/7/2.jpg", caption: "cantik bener ni orang, untung pacar aku ya" },
      { src: "/images/7/3.jpg", caption: "manis bangeeet" },
      { src: "/images/7/4.jpg", caption: "boleh cicip?" },
      { src: "/images/7/5.jpg", caption: "cantik bangeeeeet" },
      { src: "/images/7/6.jpg", caption: "lucunyaa bocil akuu" },
      { src: "/images/7/7.jpg", caption: "cantik banget deh sumpah babyy" },
      { src: "/images/7/8.jpg", caption: "ni diaa my princess" },
      { src: "/images/7/9.jpg", caption: "segemash koala" },
      { src: "/images/7/10.jpg", caption: "secantik mawar" },
      { src: "/images/7/11.jpg", caption: "secantik bulan" },
      { src: "/images/7/12.jpg", caption: "gas dipacariin" },
      { src: "/images/7/13.jpg", caption: "sabar bu makannya" },
      { src: "/images/7/14.jpg", caption: "buset dah laper bu?" },
      { src: "/images/7/15.jpg", caption: "ramen timeee" },
      { src: "/images/7/16.jpg", caption: "bobo 4" },
      { src: "/images/7/17.jpg", caption: "pipinyaaa iiih jagaiaiin" },
      { src: "/images/7/18.jpg", caption: "cantiknyooo" },
      { src: "/images/7/19.jpg", caption: "enyum roblox" },
    ],
  },
  sabar: {
    title: "My Baby ❤️",
    photos: [
      { src: "/images/8/1.jpg", caption: "gelang baruuu" },
      { src: "/images/8/2.jpg", caption: "si cantik penjajah solo" },
      { src: "/images/8/3.jpg", caption: "per pertama kali ditemukan didunia ini" },
      { src: "/images/8/4.jpg", caption: "ya ampuuun cantik banget siiih" },
      { src: "/images/8/5.jpg", caption: "pake baju aku makin cantik aja" },
      { src: "/images/8/6.jpg", caption: "dikedipin mulu, hampir copot jantung ini" },
      { src: "/images/8/7.jpg", caption: "MELET LAGIIIIIII" },
      { src: "/images/8/8.jpg", caption: "gemesh banget siih, warewolfnya mana red hoood" },
      { src: "/images/8/9.jpg", caption: "aku cium juga ni" },
      { src: "/images/8/10.jpg", caption: "First trip perjalanan jauh" },
      { src: "/images/8/11.jpg", caption: "busyet dah cakep beneeer" },
    ],
  },
}
